# Generated by Django 4.1.7 on 2023-07-18 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intensity', models.IntegerField()),
                ('likelihood', models.IntegerField()),
                ('relevance', models.IntegerField()),
                ('country', models.CharField(max_length=100)),
                ('topics', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('end_year', models.CharField(blank=True, max_length=4)),
                ('start_year', models.CharField(blank=True, max_length=4)),
                ('insight', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('impact', models.CharField(blank=True, max_length=255)),
                ('added', models.DateTimeField()),
                ('published', models.DateTimeField()),
                ('pestle', models.CharField(max_length=100)),
                ('source', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=255)),
            ],
        ),
    ]
