# Generated by Django 4.1.7 on 2023-07-18 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataentry',
            name='added',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
