# Generated by Django 4.1.7 on 2023-07-18 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_app', '0002_alter_dataentry_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataentry',
            name='published',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
